// <auto-generated />
namespace Cooperchip.aulaChagas.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TelEtpTel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TelEtpTel));
        
        string IMigrationMetadata.Id
        {
            get { return "201710191436398_TelEtpTel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
